services:
  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - "2345:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  application:
    build: .
    container_name: application
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8443:8443"
    env_file:
      - secrets.env
